Document: mdealer
Title: Debian mdealer Manual
Author: <insert document author here>
Abstract: This manual describes what mdealer is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/mdealer/mdealer.sgml.gz

Format: postscript
Files: /usr/share/doc/mdealer/mdealer.ps.gz

Format: text
Files: /usr/share/doc/mdealer/mdealer.text.gz

Format: HTML
Index: /usr/share/doc/mdealer/html/index.html
Files: /usr/share/doc/mdealer/html/*.html
