#!/bin/bash

# I suppose that the username and the groupname is the same
GROUP=`perl -e '($login,$pass,$uid,$gid) = getpwuid(1000);print "$login\n";'`

chown root:$GROUP /etc/mdealer -R
chmod g+w /etc/mdealer -R

chown root:$GROUP /etc/bluetooth/main.conf

chmod 644 /usr/lib/bonobo/servers/mdealer-applet.server

mv /etc/mdealer/db.sqlite /etc/mdealer/db.sqlite.BACKUP 2> /dev/null
